export type LifecyclePhase = 'playing' | 'celebrating' | 'awaiting-operator' | 'paused' | 'summary' | 'restart-countdown';
export type CompletionPolicy = 'immediate-advance' | 'celebration-then-advance' | 'pause' | 'operator-confirm';
export interface LifecycleConfig { readonly levelCount: number; readonly restartDelayTicks: number; readonly celebrationTicks: number }
export interface LifecycleState { readonly phase: LifecyclePhase; readonly runNumber: number; readonly currentLevel: number; readonly levelCount: number; readonly levelStreak: number; readonly pendingLevel: number | null; readonly countdownTicksRemaining: number; readonly celebrationTicksRemaining: number }
export type LifecycleCommand = { readonly type: 'tick' | 'new-game' | 'restart-current-level' | 'reset-run' | 'skip-level' | 'previous-level' | 'next-level' | 'pause' | 'resume' | 'confirm-level-advance' };
const validConfig = (config: LifecycleConfig): void => { if (!Number.isInteger(config.levelCount) || config.levelCount < 1) throw new RangeError('levelCount must be positive.'); if (!Number.isInteger(config.restartDelayTicks) || config.restartDelayTicks < 0 || !Number.isInteger(config.celebrationTicks) || config.celebrationTicks < 0) throw new RangeError('delays must be nonnegative integers.'); };
export function createLifecycleState(config: LifecycleConfig): LifecycleState { validConfig(config); return { phase:'playing', runNumber:1, currentLevel:1, levelCount:config.levelCount, levelStreak:0, pendingLevel:null, countdownTicksRemaining:0, celebrationTicksRemaining:0 }; }
const freshRun = (state: LifecycleState): LifecycleState => ({ ...state, phase:'playing', runNumber:state.runNumber+1, currentLevel:1, levelStreak:0, pendingLevel:null, countdownTicksRemaining:0, celebrationTicksRemaining:0 });
export function endRun(state: LifecycleState, config: LifecycleConfig): LifecycleState { validConfig(config); return { ...state, phase:'summary', levelStreak:0, pendingLevel:null, countdownTicksRemaining:0, celebrationTicksRemaining:0 }; }
export function completeLevel(state: LifecycleState, policy: CompletionPolicy, config: LifecycleConfig): LifecycleState { validConfig(config); const streak=state.levelStreak+1; if (state.currentLevel >= state.levelCount) return { ...state, phase:'summary', levelStreak:streak, pendingLevel:null }; const next=state.currentLevel+1; if (policy==='immediate-advance') return { ...state, phase:'playing', currentLevel:next, levelStreak:streak, pendingLevel:null, celebrationTicksRemaining:0 }; if (policy==='celebration-then-advance') return config.celebrationTicks===0 ? { ...state, phase:'playing', currentLevel:next, levelStreak:streak, pendingLevel:null } : { ...state, phase:'celebrating', levelStreak:streak, pendingLevel:next, celebrationTicksRemaining:config.celebrationTicks }; if (policy==='pause') return { ...state, phase:'paused', levelStreak:streak, pendingLevel:next }; return { ...state, phase:'awaiting-operator', levelStreak:streak, pendingLevel:next }; }
export function reduceLifecycle(state: LifecycleState, command: LifecycleCommand, config: LifecycleConfig): LifecycleState { validConfig(config); const advancePending=():LifecycleState => state.pendingLevel===null ? { ...state } : { ...state, phase:'playing', currentLevel:state.pendingLevel, pendingLevel:null, celebrationTicksRemaining:0, countdownTicksRemaining:0 };
  if (command.type==='tick') { if (state.phase==='summary') return config.restartDelayTicks===0 ? freshRun(state) : { ...state, phase:'restart-countdown', countdownTicksRemaining:config.restartDelayTicks }; if (state.phase==='restart-countdown') return state.countdownTicksRemaining<=1 ? freshRun(state) : { ...state, countdownTicksRemaining:state.countdownTicksRemaining-1 }; if (state.phase==='celebrating') return state.celebrationTicksRemaining<=1 ? advancePending() : { ...state, celebrationTicksRemaining:state.celebrationTicksRemaining-1 }; return { ...state }; }
  if (command.type==='new-game' || command.type==='reset-run') return freshRun(state);
  if (command.type==='restart-current-level') return { ...state, phase:'playing', pendingLevel:null, countdownTicksRemaining:0, celebrationTicksRemaining:0 };
  if (command.type==='pause') return state.phase==='playing' ? { ...state, phase:'paused' } : { ...state };
  if (command.type==='resume') return state.phase==='paused' ? (state.pendingLevel===null ? { ...state, phase:'playing' } : advancePending()) : { ...state };
  if (command.type==='confirm-level-advance') return state.phase==='awaiting-operator' ? advancePending() : { ...state };
  if (command.type==='next-level' || command.type==='skip-level') return { ...state, phase:'playing', currentLevel:Math.min(state.levelCount,state.currentLevel+1), pendingLevel:null };
  if (command.type==='previous-level') return { ...state, phase:'playing', currentLevel:Math.max(1,state.currentLevel-1), pendingLevel:null };
  return { ...state };
}
