import type { DeathCause } from '@snake/engine';
import type { RecordMarker } from './records.js';
export interface SpectatorDeath { readonly internalCause: DeathCause; readonly label: string; readonly source: 'natural' | 'configured-deviation'; readonly deviationId?: string }
export interface RunSummary { readonly runNumber: number; readonly levelNumber: number; readonly outcome: string; readonly death: SpectatorDeath | null; readonly ticksSurvived: number; readonly maxLength: number; readonly maxOccupancyPercent: number; readonly score: number; readonly foodConsumed: number; readonly levelCompleted: boolean; readonly newRecords: readonly RecordMarker[]; readonly milestones: readonly unknown[]; readonly nearDeaths: readonly unknown[]; readonly highlights: readonly string[] }
const labels: Record<DeathCause,string> = { 'wall-collision':'WALL IMPACT', 'self-collision':'SELF COLLISION', 'obstacle-collision':'OBSTACLE IMPACT', 'hazard-collision':'HAZARD HIT', 'bounds-collision':'ARENA COLLAPSE' };
export function classifyDeath(cause: DeathCause, attribution?: { readonly category?: string; readonly contributory?: boolean; readonly deviationId?: string }): SpectatorDeath {
  if (attribution?.category === 'configured-deviation' && attribution.contributory && attribution.deviationId) return { internalCause: cause, label: labels[cause], source: 'configured-deviation', deviationId: attribution.deviationId };
  return { internalCause: cause, label: labels[cause], source: 'natural' };
}
const markerLabel = (marker: string): string => marker.toUpperCase().replaceAll('-', ' ');
export function buildRunSummary(input: { readonly runNumber: number; readonly levelNumber: number; readonly terminalReason: string; readonly deathCause: DeathCause | null; readonly ticksSurvived: number; readonly maxLength: number; readonly maxOccupancyPercent: number; readonly score: number; readonly foodConsumed: number; readonly levelCompleted: boolean; readonly newRecords: readonly RecordMarker[]; readonly milestones?: readonly unknown[]; readonly nearDeaths?: readonly unknown[]; readonly attribution?: { readonly category?: string; readonly contributory?: boolean; readonly deviationId?: string } }): RunSummary {
  return { runNumber: input.runNumber, levelNumber: input.levelNumber, outcome: input.levelCompleted ? 'completed' : input.terminalReason, death: input.deathCause ? classifyDeath(input.deathCause, input.attribution) : null, ticksSurvived: input.ticksSurvived, maxLength: input.maxLength, maxOccupancyPercent: input.maxOccupancyPercent, score: input.score, foodConsumed: input.foodConsumed, levelCompleted: input.levelCompleted, newRecords: [...input.newRecords], milestones: [...(input.milestones ?? [])], nearDeaths: [...(input.nearDeaths ?? [])], highlights: input.newRecords.map((marker) => `NEW RECORD: ${markerLabel(marker)}`) };
}
